import {
  Shield,
  Lock,
  Eye,
  Key,
  FileCheck,
  AlertTriangle,
  Server,
  UserCheck,
  Globe,
  CheckCircle2,
} from "lucide-react";
import { SectionCard } from "../components/SectionCard";

const securityLayers = [
  {
    title: "Network Security",
    icon: <Globe className="w-5 h-5" />,
    items: ["WAF (Web Application Firewall)", "DDoS Protection (Cloudflare)", "VPN cho internal access", "Network segmentation", "SSL/TLS everywhere"],
  },
  {
    title: "Application Security",
    icon: <Shield className="w-5 h-5" />,
    items: ["OWASP Top 10 protection", "Input validation & sanitization", "CSRF/XSS prevention", "Rate limiting & throttling", "API security (OAuth 2.0 + JWT)"],
  },
  {
    title: "Data Security",
    icon: <Lock className="w-5 h-5" />,
    items: ["Encryption at rest (AES-256)", "Encryption in transit (TLS 1.3)", "Data masking for PII", "Backup encryption", "Key management (AWS KMS)"],
  },
  {
    title: "Access Control",
    icon: <Key className="w-5 h-5" />,
    items: ["RBAC (Role-Based Access Control)", "MFA (Multi-Factor Authentication)", "SSO integration (SAML/OIDC)", "Principle of least privilege", "Session management"],
  },
  {
    title: "AI Security",
    icon: <Eye className="w-5 h-5" />,
    items: ["AI action audit trail", "Prompt injection prevention", "AI output validation", "Model access control", "AI decision explainability"],
  },
  {
    title: "Compliance",
    icon: <FileCheck className="w-5 h-5" />,
    items: ["GDPR compliance", "SOC 2 Type II", "ISO 27001", "Data retention policies", "Right to be forgotten"],
  },
];

const auditFeatures = [
  "Mọi hành động user được log với timestamp, IP, device",
  "AI agent actions logged với input/output/model/confidence",
  "Data access patterns monitored & anomaly detection",
  "Admin actions require approval workflow",
  "Monthly security audit reports auto-generated by AI",
  "Real-time alerting cho suspicious activities",
  "Immutable audit log (append-only, no delete)",
  "Compliance dashboard real-time",
];

export function SecurityPage() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-gray-900">🔒 Bảo mật & Tuân thủ</h1>
        <p className="text-gray-500 mt-1">
          Defense-in-depth security architecture với AI-powered threat detection
        </p>
      </div>

      {/* Security Layers */}
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        {securityLayers.map((layer) => (
          <SectionCard key={layer.title} title={layer.title} icon={layer.icon}>
            <div className="space-y-2">
              {layer.items.map((item) => (
                <div key={item} className="flex items-center gap-2 text-sm text-gray-600">
                  <CheckCircle2 className="w-3.5 h-3.5 text-green-500 flex-shrink-0" />
                  {item}
                </div>
              ))}
            </div>
          </SectionCard>
        ))}
      </div>

      {/* Audit & Transparency */}
      <SectionCard
        title="Audit Trail & Transparency"
        subtitle="100% minh bạch - Mọi hành động được ghi nhận"
        icon={<UserCheck className="w-5 h-5" />}
      >
        <div className="grid md:grid-cols-2 gap-3">
          {auditFeatures.map((f) => (
            <div key={f} className="flex items-start gap-2 p-3 bg-green-50 rounded-lg text-sm text-green-800">
              <CheckCircle2 className="w-4 h-4 text-green-500 mt-0.5 flex-shrink-0" />
              {f}
            </div>
          ))}
        </div>
      </SectionCard>

      {/* AI-Specific Security */}
      <SectionCard
        title="AI-Specific Security Measures"
        subtitle="Bảo mật riêng cho hệ thống AI"
        icon={<AlertTriangle className="w-5 h-5" />}
      >
        <div className="grid md:grid-cols-2 gap-4">
          {[
            {
              title: "AI Decision Explainability",
              desc: "Mọi quyết định AI phải có giải thích rõ ràng. Nhân viên có thể xem lý do AI đánh giá, scoring, recommendations.",
            },
            {
              title: "Human Override Protocol",
              desc: "Con người luôn có quyền override quyết định AI. Mọi override được log và AI học từ feedback.",
            },
            {
              title: "AI Bias Detection",
              desc: "Hệ thống tự động detect bias trong AI scoring. Monthly audit cho fairness metrics across demographics.",
            },
            {
              title: "Data Privacy for AI",
              desc: "AI không được training trên PII trực tiếp. Anonymization & differential privacy techniques.",
            },
            {
              title: "Model Versioning & Rollback",
              desc: "Mọi AI model version controlled. Rollback tức thì nếu phát hiện vấn đề quality.",
            },
            {
              title: "AI Rate Limiting",
              desc: "Giới hạn số lượng AI actions per minute. Prevent runaway AI agents và cost control.",
            },
          ].map((item) => (
            <div key={item.title} className="p-4 rounded-xl border border-gray-100 hover:border-amber-200 transition-colors">
              <h4 className="text-sm text-gray-900 mb-1">{item.title}</h4>
              <p className="text-xs text-gray-500 leading-relaxed">{item.desc}</p>
            </div>
          ))}
        </div>
      </SectionCard>

      {/* Infrastructure Security */}
      <SectionCard
        title="Infrastructure Security"
        icon={<Server className="w-5 h-5" />}
      >
        <div className="space-y-2">
          {[
            { item: "Container Security", detail: "Docker image scanning, runtime protection, pod security policies" },
            { item: "Secret Management", detail: "HashiCorp Vault, encrypted secrets, rotation policies" },
            { item: "Monitoring & SIEM", detail: "Centralized logging (ELK), SIEM (Splunk), real-time alerting" },
            { item: "Disaster Recovery", detail: "RPO < 1h, RTO < 4h, multi-region backup, automated failover" },
            { item: "Penetration Testing", detail: "Quarterly pen testing, bug bounty program, vulnerability management" },
          ].map((s) => (
            <div key={s.item} className="flex items-start gap-3 p-3 rounded-lg hover:bg-gray-50">
              <Shield className="w-4 h-4 text-violet-600 mt-0.5 flex-shrink-0" />
              <div>
                <p className="text-sm text-gray-900">{s.item}</p>
                <p className="text-xs text-gray-500">{s.detail}</p>
              </div>
            </div>
          ))}
        </div>
      </SectionCard>
    </div>
  );
}
